
classes:
- system.linux.system.single
#- system.openssh.server.team.lab
#- system.openssh.server.team.support
#- system.openssh.server.team.presales
#- system.openssh.server.team.services
#- system.openssh.server.team.networking
#- system.openssh.server.team.stacklight
#- system.openssh.server.team.mmo_devops
- system.rsyslog.client.single
- cluster.mcp_upgrade.openstack
- cluster.mcp_upgrade.cicd
parameters:
  _param:
    # TODO: Uncomment next line "linux_system_user_sudo: true" during the deployment.
    # Don't set it "false" before you configure sudo policies and enable power users.
    # linux_system_user_sudo: true
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.1.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.1.qcow2
    infra_config_hostname: cfg01
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    # infra service addresses
    infra_config_address: 10.0.1.6
    infra_config_deploy_address: 10.0.0.15

    cluster_domain: mcp_upgrade.local
    cluster_name: mcp_upgrade
    cluster_public_host: ${_param:openstack_proxy_address}

    control_network_netmask: 255.255.255.0
    tenant_network_netmask: 255.255.255.0

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    control_vlan: 10
    tenant_vlan: 20

    deploy_network_netmask: 255.255.255.0
    deploy_network_gateway: 10.0.0.1

    # MaaS parameters
    infra_maas_node01_deploy_address: 10.0.0.16
    infra_maas_node01_hostname: mas01
    maas_admin_username: mirantis
    maas_admin_password: 2pohCuhi4htpUvj3
    maas_db_password: REPLACE_BY_GENERATED_VALUE_DURING_INSTALL
    infra_kvm_address: 10.0.1.240
    infra_kvm_node01_address: 10.0.1.11
    infra_kvm_node02_address: 10.0.1.12
    infra_kvm_node03_address: 10.0.1.13
    infra_kvm_node01_deploy_address: 10.0.0.12
    infra_kvm_node02_deploy_address: 10.0.0.13
    infra_kvm_node03_deploy_address: 10.0.0.14
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
    glusterfs_node03_address: ${_param:infra_kvm_node03_address}

    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}

  salt:
    minion:
      trusted_ca_minions:
        - ${_param:salt_minion_ca_host}

  linux:
    network:
      host:
        hostname:
          address: ${_param:single_address}
          names:
          - ${linux:network:hostname}
          - ${linux:network:fqdn}
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      service:
        apt-daily.timer:
          status: dead
